# Site settings
title: PANDORA
client:
  name: PANDORA
  link: "http://estore-uk.pandora.net/valentine-s/?cid=em:ge:e:en-gb::::VAL18:ot:"
description: Enter our exclusive competition to be in with a chance of winning your ideal getaway, whether you fancy a romantic sojourn with your partner or wish to kick-back with your beloved family.

baseurl: "/pandora" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [js/scripts.min.js]
sass:
    sass_dir: css
    style: compressed