
- title: Two Hearts Hoop Earrings
  id: two-hearts-hoop-earrings

- title: Silver Key Locket
  id: silver-key-locket

- title: Love Lock Ring
  id: love-lock-ring

- title: Moments Silver Lock Your Promise Heart Clasp Bracelet
  id: moments-smooth-silver-bracelet

- title: Two Hearts Ring
  id: two-hearts-open-silver-ring

- title: I Love You Pendant Charm
  id: i-love-you-two-tone-pendant-charm

- title: Shining Elegance Clip
  id: rose-shining-elegance-clip

- title: Two Hearts Spacer
  id: rose-two-hearts-spacer

- title: Two Hearts Ring
  id: rose-two-hearts-ring

- title: Explosion of Love Charm
  id: explosion-of-love-charm

- title: Pink Heart Key Locket Necklace
  id: pink-floating-locket-heart-key

- title: Kisses All Around Glass Murano Charm
  id: kisses-all-around-glass-charm

- title: Dazzling Droplets Stud Earrings
  id: gold-dazzling-droplets-stud-earrings

- title: Classic Elegance Ring
  id: rose-classic-elegance-ring

- title: Puzzle Heart Ring
  id: two-tone-puzzle-heart-ring

- title: July Droplet Birthstone Ring
  id: july-birthstone-ring

- title: ESSENCE PANDORA Rose Bracelet
  id: rose-essence-bracelet
